INSERT INTO PAYMENT_TRANSACTION(AMOUNT,PAYMENT_METHOD_TYPE, STATUS) VALUES (112.87,'CREDIT_CARD', 'NEW');

INSERT INTO ORDER_ITEM(PRODUCT_NAME, QUANTITY, PRICE, PAYMENT_TRANSACTION_ID) VALUES ('LAPTOP', 2, 10.99, 1);
INSERT INTO ORDER_ITEM(PRODUCT_NAME, QUANTITY, PRICE, PAYMENT_TRANSACTION_ID) VALUES ('CARTRIDGE', 1, 5.99, 1);
INSERT INTO ORDER_ITEM(PRODUCT_NAME, QUANTITY, PRICE, PAYMENT_TRANSACTION_ID) VALUES ('FLASH USB', 5, 29.99, 1);
INSERT INTO ORDER_ITEM(PRODUCT_NAME, QUANTITY, PRICE, PAYMENT_TRANSACTION_ID) VALUES ('EXTERNAL HARD DRIVE', 88.75, 10, 1);